timeline:
    resource: "@TimelineBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: "@TimelineBundle/Controller/"
    type:     annotation

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# API
timeline_api_cat:
    # По пути с любым ID или all
    path:  /api/cat/{id}/
    path:  /api/cat/{id}
    # Направляем в метод
    defaults: { _controller: TimelineApiBundle:Cat:get, _format: ~ }
    # И передаём ID
    requirements:
        _method: GET
        # Пропускает любое кол-во цифр или 'all'
        id: '(\d+|all)'

timeline_api_event_by_cat:
    # По пути с любым ID или all
    path:  /api/event/cat/{id}/
    path:  /api/event/cat/{id}
    # Направляем в метод
    defaults: { _controller: TimelineApiBundle:Event:getByCat, _format: ~ }
    # И передаём ID
    requirements:
        _method: GET
        # Пропускает любое кол-во цифр или 'all'
        id: '(\d+)'

#TODO later
timeline_api_event:
    path:  /api/event/
    defaults: { _controller: TimelineApiBundle:Event:Route, _format: ~ }
