# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.cat:
        class: TimelineBundle\Admin\CatAdmin
        arguments: [~, TimelineBundle\Entity\Cat, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Котик }

    admin.event:
        class: TimelineBundle\Admin\EventAdmin
        arguments: [~, TimelineBundle\Entity\Cat, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Событие }

