TimelineBundle\Entity\Cat:
    type: entity
    table: cat
    repositoryClass: TimelineBundle\Repository\CatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        photo:
            type: string
            length: 255
            nullable: true
        datebirth:
            type: datetime
            nullable: true

    lifecycleCallbacks:
      prePersist:   [ lifecycleFileUpload ]
      preUpdate:    [ lifecycleFileUpload ]
