TimelineBundle\Entity\Event:
    type: entity
    table: events
    repositoryClass: TimelineBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        catId:
            type: integer
        time:
            type: datetime
        photo:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        weight:
            type: integer
            nullable: true

    lifecycleCallbacks:
      prePersist:   [ lifecycleFileUpload ]
      preUpdate:    [ lifecycleFileUpload ]