TimelineBundle\Entity\Event:
    type: entity
    table: events
    repositoryClass: TimelineBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cat:
            type: integer
        time:
            type: time
        photo:
            type: string
            length: 255
        description:
            type: text
        weight:
            type: integer

    lifecycleCallbacks:
      prePersist:   [ lifecycleFileUpload ]
      preUpdate:    [ lifecycleFileUpload ]